[SDK-549] Add public user id getter
d4l-data4life/d4l-sdk-ios pull request #23
Opened 2021-05-03 13:40 UTC by alessioborraccino

## Description

Adds a public way to get userID from the client.

## Motivation and Context

Raising the need to tag resources with something related to the user account, we decided to make the userId available from fetching from outside.

## How is it being implemented?

Adds a new API from the client to get the user ID which fails in case user is not logged in.

## How Has This Been Tested?

Adds new tests for the new api calls:
* UserService unit tests
* Data4LifeClient unit tests
* Data4LifeClient + UserService module tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the changelog accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-05-03 15:24 UTC, jose-cuadros-data4life requested changes

2021-05-03 15:24 UTC, jose-cuadros-data4life commented on SDK/Sources/Client/Data4LifeClient+User.swift
> +     - parameter completion:Completion that returns the userID connected with the account.
Just a small fix: `completion: Completion`

2021-05-03 15:24 UTC, jose-cuadros-data4life commented on SDK/Sources/Services/UserService.swift
> +        try `await`(self.keychainService.get(.userId))
We could use `wait` from the other PR

2021-05-03 15:24 UTC, jose-cuadros-data4life commented on SDK/Tests/ModuleTests/Data4LifeClient+UserServiceModuleTests.swift
> +//  All rights reserved.
Nice tests in this file! 🎉

2021-05-04 08:29 UTC, jose-cuadros-data4life approved these changes
Lgtm

2021-05-04 08:38 UTC, merged

2021-05-04 08:38 UTC, ztepsa commented on SDK/Tests/ClientTests/Data4LifeClient+UserTests.swift
> +        let asyncExpectation = expectation(description: "should return response with count on UI thread")
Can we update expectation description so it reflects what's really going on, something like:
```
should return userId on on UI thread
```
Also we can assert that we'r on the proper thread if needed.
```swift
XCTAssertTrue(Thread.isMainThread)
```