[SDK-615] Add new query parameters and metadata status
d4l-data4life/d4l-sdk-ios pull request #54
Opened 2021-09-28 16:28 UTC by alessioborraccino

## Description

## Motivation and Context

## How is it being implemented?

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the changelog accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-11-11 10:26 UTC, jose-cuadros-data4life requested changes

2021-11-18 09:59 UTC, alessioborraccino commented on asciidoc/04_sdk_api.adoc
> +                                               includingDeleted: Bool = false,
done 👍

2021-11-23 09:07 UTC, jose-cuadros-data4life commented on asciidoc/04_sdk_api.adoc
> +                                               includingDeleted: Bool = false,
Thanks!

2021-11-23 09:09 UTC, jose-cuadros-data4life approved these changes
Lgtm!

2021-11-23 09:15 UTC, merged